Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200
